[06/Jul/2022 07:15:22] INFO [django.utils.autoreload:617] Watching for file changes with StatReloader
[06/Jul/2022 07:15:22] INFO [django.utils.autoreload:617] Watching for file changes with StatReloader
[06/Jul/2022 07:15:29] INFO [django.server:157] "GET / HTTP/1.1" 200 15059
[06/Jul/2022 07:15:29] INFO [django.server:157] "GET / HTTP/1.1" 200 15059
[06/Jul/2022 07:15:29] INFO [django.server:157] "GET /static/application/styles.css HTTP/1.1" 304 0
[06/Jul/2022 07:15:29] INFO [django.server:157] "GET /static/application/styles.css HTTP/1.1" 304 0
[06/Jul/2022 07:15:29] INFO [django.server:157] "GET /static/application/images/CityLogoWhite-01.png HTTP/1.1" 304 0
[06/Jul/2022 07:15:29] INFO [django.server:157] "GET /static/application/images/CityLogoWhite-01.png HTTP/1.1" 304 0
[06/Jul/2022 07:15:29] INFO [django.server:157] "GET /static/application/images/WelcomeIllustration.svg HTTP/1.1" 304 0
[06/Jul/2022 07:15:29] INFO [django.server:157] "GET /static/application/images/WelcomeIllustration.svg HTTP/1.1" 304 0
[06/Jul/2022 07:15:29] INFO [django.server:157] "GET /static/application/images/control.png HTTP/1.1" 304 0
[06/Jul/2022 07:15:29] INFO [django.server:157] "GET /static/application/images/control.png HTTP/1.1" 304 0
[06/Jul/2022 07:15:29] INFO [django.server:157] "GET /static/application/images/control.svg HTTP/1.1" 304 0
[06/Jul/2022 07:15:29] INFO [django.server:157] "GET /static/application/images/control.svg HTTP/1.1" 304 0
[06/Jul/2022 07:15:29] INFO [django.server:157] "GET /static/application/images/save.png HTTP/1.1" 304 0
[06/Jul/2022 07:15:29] INFO [django.server:157] "GET /static/application/images/save.png HTTP/1.1" 304 0
[06/Jul/2022 07:15:29] INFO [django.server:157] "GET /static/application/images/save.svg HTTP/1.1" 304 0
[06/Jul/2022 07:15:29] INFO [django.server:157] "GET /static/application/images/save.svg HTTP/1.1" 304 0
[06/Jul/2022 07:15:29] INFO [django.server:157] "GET /static/application/images/forget.png HTTP/1.1" 304 0
[06/Jul/2022 07:15:29] INFO [django.server:157] "GET /static/application/images/forget.png HTTP/1.1" 304 0
[06/Jul/2022 07:15:29] INFO [django.server:157] "GET /static/application/images/forget.svg HTTP/1.1" 304 0
[06/Jul/2022 07:15:29] INFO [django.server:157] "GET /static/application/images/forget.svg HTTP/1.1" 304 0
[06/Jul/2022 07:15:29] INFO [django.server:157] "GET /static/application/images/know.png HTTP/1.1" 304 0
[06/Jul/2022 07:15:29] INFO [django.server:157] "GET /static/application/images/know.png HTTP/1.1" 304 0
[06/Jul/2022 07:15:29] INFO [django.server:157] "GET /static/application/images/know.svg HTTP/1.1" 304 0
[06/Jul/2022 07:15:29] INFO [django.server:157] "GET /static/application/images/know.svg HTTP/1.1" 304 0
[06/Jul/2022 07:15:29] INFO [django.server:157] "GET /static/application/images/X_gray.svg HTTP/1.1" 304 0
[06/Jul/2022 07:15:29] INFO [django.server:157] "GET /static/application/images/X_gray.svg HTTP/1.1" 304 0
[06/Jul/2022 07:23:11] INFO [django.server:157] "GET /application/finances HTTP/1.1" 200 10803
[06/Jul/2022 07:23:11] INFO [django.server:157] "GET /application/finances HTTP/1.1" 200 10803
[06/Jul/2022 07:23:11] INFO [django.server:157] "GET /static/application/styles_app.css HTTP/1.1" 304 0
[06/Jul/2022 07:23:11] INFO [django.server:157] "GET /static/application/styles_app.css HTTP/1.1" 304 0
[06/Jul/2022 07:23:12] INFO [django.server:157] "GET /static/scripts/main.js HTTP/1.1" 304 0
[06/Jul/2022 07:23:12] INFO [django.server:157] "GET /static/scripts/main.js HTTP/1.1" 304 0
[06/Jul/2022 07:23:12] INFO [django.server:157] "GET /static/application/images/CityLogoWhite-01.png HTTP/1.1" 304 0
[06/Jul/2022 07:23:12] INFO [django.server:157] "GET /static/application/images/CityLogoWhite-01.png HTTP/1.1" 304 0
[06/Jul/2022 07:23:12] INFO [django.server:157] "GET /static/application/images/BackArrow-darkblue.svg HTTP/1.1" 304 0
[06/Jul/2022 07:23:12] INFO [django.server:157] "GET /static/application/images/BackArrow-white.svg HTTP/1.1" 304 0
[06/Jul/2022 07:23:12] INFO [django.server:157] "GET /static/application/images/BackArrow-white.svg HTTP/1.1" 304 0
[06/Jul/2022 07:23:12] INFO [django.server:157] "GET /static/application/images/BackArrow-darkblue.svg HTTP/1.1" 304 0
[06/Jul/2022 07:23:22] INFO [django.server:157] "GET /application/ajax/load-gahi/?dependents=1 HTTP/1.1" 200 613
[06/Jul/2022 07:23:22] INFO [django.server:157] "GET /application/ajax/load-gahi/?dependents=1 HTTP/1.1" 200 613
[06/Jul/2022 07:23:25] ERROR [django.request:224] Internal Server Error: /application/finances
Traceback (most recent call last):
  File "C:\Users\JAndr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\JAndr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JAndr\OneDrive\Projects\GetFoCo\GetFoco\mobileVers\application\views.py", line 629, in finances
    instance.user_id = request.user
  File "C:\Users\JAndr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\db\models\fields\related_descriptors.py", line 310, in __set__
    super().__set__(instance, value)
  File "C:\Users\JAndr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\db\models\fields\related_descriptors.py", line 215, in __set__
    raise ValueError(
ValueError: Cannot assign "<SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x0000022216AE0E20>>": "Eligibility.user_id" must be a "User" instance.
[06/Jul/2022 07:23:25] ERROR [django.request:224] Internal Server Error: /application/finances
Traceback (most recent call last):
  File "C:\Users\JAndr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\JAndr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\JAndr\OneDrive\Projects\GetFoCo\GetFoco\mobileVers\application\views.py", line 629, in finances
    instance.user_id = request.user
  File "C:\Users\JAndr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\db\models\fields\related_descriptors.py", line 310, in __set__
    super().__set__(instance, value)
  File "C:\Users\JAndr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\db\models\fields\related_descriptors.py", line 215, in __set__
    raise ValueError(
ValueError: Cannot assign "<SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x0000022216AE0E20>>": "Eligibility.user_id" must be a "User" instance.
[06/Jul/2022 07:23:25] ERROR [django.server:157] "POST /application/finances HTTP/1.1" 500 145
[06/Jul/2022 07:23:25] ERROR [django.server:157] "POST /application/finances HTTP/1.1" 500 145
[06/Jul/2022 07:23:27] INFO [django.server:157] "GET /application/finances HTTP/1.1" 200 10803
[06/Jul/2022 07:23:27] INFO [django.server:157] "GET /application/finances HTTP/1.1" 200 10803
[06/Jul/2022 07:23:59] INFO [django.utils.autoreload:240] C:\Users\JAndr\OneDrive\Projects\GetFoCo\GetFoco\mobileVers\mobileVers\settings\dev.py changed, reloading.
[06/Jul/2022 07:23:59] INFO [django.utils.autoreload:240] C:\Users\JAndr\OneDrive\Projects\GetFoCo\GetFoco\mobileVers\mobileVers\settings\dev.py changed, reloading.
